### PR TITLE
Client-side script robustness

### PR DESCRIPTION
**Pull request by sneakypete81**
When using WDIO to test a Firefox Webextension, the Geckodriver context can be set to "chrome" in order to control elements of the browser itself (toolbar, browser popups, etc.). In this context, several document attributes are not available (head, body, documentElement, etc.).

It would be useful to use webdriver-image-comparison in this context. Currently the client-side scripts fail when attempting to add/remove custom CSS and when obtaining the body/html attributes during getScreenDimensions. None of this is necessary in this context.

In this PR I've added null checks to prevent the client-side scripts from failing if these document attributes are not available.

### CODE REVIEW

**Comment by sneakypete81** [comment]
Tests added - and thanks, this utility is really useful.

**Comment by wswebcreation** [comment]
@sneakypete81 

Thanks for the update, currently at the airport, will create a new release when I'm back, will be end of the day or else tomorrow.

**Comment by wswebcreation** [comment]
@sneakypete81 

Tnx for the work, I've just released `v0.4.8`. Remove all `node_modules` and the `package-lock.json` from your project and do a new install and it will automatically get the right version

**Comment by sneakypete81** [comment]
Nice one, thanks!

**Pull request merged**
